feature: Upgrade CircleCI to version 2
codacy/codacy-api-java pull request #7
Opened 2019-02-25 10:51 UTC by andreaTP

Not a big improvement, but at least this project will not stop to compile in a couple of weeks.

2019-02-25 10:57 UTC, rtfpessoa requested changes
I am not sure I understand this change:
* The new script doesn't do the same operations as the old one, why?
* When updating we should start publishing too to avoid double work, just updating is not very helpful since you will have to do it next time.

2019-02-25 11:03 UTC, andreaTP commented
The current script is doing the same as the old circle 1 job.
Yes, the publishing part has to be done, but it's a more beef work, this is just a road-unblocker since jobs are pending forever in CI ATM.

2019-02-26 20:33 UTC, paulopontesm approved these changes

2019-03-04 13:23 UTC, rtfpessoa commented
Replaced by #8

2019-03-04 13:23 UTC, closed without merging